name: flutter_movil
version: 0.1.0+1
description: Momentus Mobile - app nativa Flutter con experiencia simple, eficiente y rÃ¡pida.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.0
  # Firebase / Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  # Charts for Reports
  fl_chart: ^0.68.0
  # Biometric Authentication
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
